### ISSUE TITLE
Provide default tab size for repository

### ISSUE THREAD

**Issue by marcohu** [esoco/coroutines#4]
As you prefer tabs, but your tab size differs from the Github default, you should provide an `.editorconfig` to have the files display correctly. 

For reference:
https://stackoverflow.com/questions/8833953/how-to-change-tab-size-on-github#33831598

This is what it looks like currently by default:

![tabs](https://user-images.githubusercontent.com/487062/48833467-b2b88e80-ed7b-11e8-81f2-59c73cae2087.png)

**Comment by esocode** [comment]
Thanks for the hint, I wasn't aware of that feature 👍  Added it.
